### ISSUE TITLE
Remove not needed request on login page /api/user/get/unread_messages

### ISSUE THREAD

**Issue by rokj** [MeetPlan/MeetPlanFrontend#53]
![Screenshot from 2022-08-10 18-46-49](https://user-images.githubusercontent.com/145760/183968939-320219e6-e166-41bb-8533-4d346bcd94b0.png)

**Comment by mytja** [comment]
Fixed by https://github.com/MeetPlan/MeetPlanFrontend/commit/e5ec3becc00436c7b3fd9aa5edd684cc3fb44546
